### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by bersbersbers** [vbaderks/ConvertProjDepToProjRef#17]
First issue! And it's not a real issue after all, since this tool just saved me *hours* of work. Thank you!

But maybe a suggestion: could you (make GitHub) release binaries? In fact, it took me longer to download and install a C# compiler in my Visual Studio than to actually use the tool :)

(Oh, #17. Not the very first one, then.)

**Comment by vbaderks** [comment]
Thanks for the feedback. Added a binary to the release page.

Note: This was actually the first issue :-). GitHub uses a single counter for pull requests and issues.

**Comment by bersbersbers** [comment]
Awesome, thanks!
